### ISSUE TITLE
Can't parse json object traversal

### ISSUE THREAD

**Issue by johannesclaesson** [gruebel/pycep#32]
Given a bicep line like:
var subscriptions = json(loadTextContent('./vars.json')).subscriptions

and vars.json contents like:
```
{
  "subscriptions": {
    "prod": {
      "id": "an id"
    }
  }
}
```
pycep will fail on "[...] .subscriptions"
This syntax is syntactically correct and briefly referenced in [official documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-files#remarks-1)

```
2022-05-15 22:02:40,670 [MainThread  ] [ERROR]  [bicep] Couldn't parse test_json.bicep
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/lark/lexer.py", line 528, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/home/username/.local/lib/python3.10/site-packages/lark/lexer.py", line 466, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: <unprintable UnexpectedCharacters object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/checkov/bicep/parser.py", line 20, in parse
    template = self.bicep_parser.parse(text=content)
  File "/home/username/.local/lib/python3.10/site-packages/pycep/main.py", line 23, in parse
    tree = self._create_tree(text=text, file_path=file_path)
  File "/home/username/.local/lib/python3.10/site-packages/pycep/main.py", line 41, in _create_tree
    return self.lark_parser.parse(bicep_text)
  File "/home/username/.local/lib/python3.10/site-packages/lark/lark.py", line 625, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/home/username/.local/lib/python3.10/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/home/username/.local/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/home/username/.local/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/home/username/.local/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state 
    raise e
  File "/home/username/.local/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state 
    for token in state.lexer.lex(state):
  File "/home/username/.local/lib/python3.10/site-packages/lark/lexer.py", line 537, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: <unprintable UnexpectedToken object>
```

**Comment by gruebel** [comment]
@johannesclaesson thanks, nice find! Always happy to get some more real world usage examples, which should be supported. The `pycep-parser` won't parse the content of the json file, but I missed to add the possibility that a property accessor can used in combination with `json().something`.
